In [1]:
%cd ..
%cd ..

/home/wu/Repos/gesture/gan/gesture-wgan/tools
/home/wu/Repos/gesture/gan/gesture-wgan


In [2]:
import pickle
import numpy as np

np.random.seed(1)

In [3]:
# Load data
with open('data/takekuchi/processed/prosody/X_dev.p', 'rb') as f:
    X_test = pickle.load(f)

In [4]:
# Filter shorter than 10 secondsS
idxs = [i for i, x in enumerate(X_test) if len(x) > 300]

# Randomly seletect samples from dataset for exp
idxs = sorted(np.random.choice(idxs, size=5, replace=False))
print(idxs)

[13, 14, 19, 22, 34]


In [5]:
idxs = np.array(idxs)*2 + 1093
print(idxs)

[1119 1121 1131 1137 1161]


In [6]:
# order of audio
idxs = [1, 12, 23]
np.random.shuffle(idxs)
print(idxs)

[12, 23, 1]


In [7]:
# order of muted video
idxs = [2, 3, 4, 5, 6, 13, 14, 15, 16, 17, 24, 25, 26, 27, 28]
np.random.shuffle(idxs)
print(idxs)

[16, 5, 28, 17, 2, 14, 3, 15, 26, 27, 24, 25, 6, 4, 13]


In [8]:
# order of video
idxs = [7, 8, 9, 10, 11, 18, 19, 20, 21, 22, 29, 30, 31, 32, 33]
np.random.shuffle(idxs)
print(idxs)

[31, 21, 9, 11, 10, 18, 32, 30, 29, 7, 8, 33, 19, 20, 22]


In [9]:
# order of commu video
idxs = np.arange(34, 49)
np.random.shuffle(idxs)
print(idxs)

[44 47 36 45 48 43 34 38 46 35 39 40 37 41 42]


In [10]:
# order of commu video
idxs = np.arange(49, 64)
np.random.shuffle(idxs)
print(idxs)

[61 57 54 60 56 55 59 50 53 63 51 58 52 62 49]
